"use client";
import { FormEvent, useEffect, useState } from "react";
type Repository = { id: string; name: string; url: string; status: string; file_count: number; branch?: string; error?: string };
const API_URL = process.env.NEXT_PUBLIC_API_URL ?? "http://localhost:8000";
export default function Dashboard() {
  const [repositories, setRepositories] = useState<Repository[]>([]); const [url, setUrl] = useState(""); const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false); const [authenticated, setAuthenticated] = useState(false);
  async function loadRepositories() { const response = await fetch(`${API_URL}/repositories`, { credentials: "include" }); if (response.ok) setRepositories((await response.json()).repositories); }
  async function loadSession() { const response = await fetch(`${API_URL}/auth/me`, { credentials: "include" }); if (response.ok && (await response.json()).authenticated) { setAuthenticated(true); await loadRepositories(); } }
  useEffect(() => { loadSession(); }, []);
  async function importRepository(event: FormEvent) { event.preventDefault(); setError(""); setSubmitting(true); try { const response = await fetch(`${API_URL}/repositories`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ url }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail ?? "Import failed"); setRepositories((current) => [data, ...current]); setUrl(""); } catch (caught) { setError(caught instanceof Error ? caught.message : "Import failed"); } finally { setSubmitting(false); } }
  return <main className="shell"><nav className="topbar"><div className="brand"><span className="brand-mark">◈</span><span>veridexs</span></div><a className="github-link" href={`${API_URL}/auth/github/login`}>Connect GitHub <span>↗</span></a></nav><section className="hero"><p className="eyebrow">ENGINEERING INTELLIGENCE / 01</p><h1>Your codebase,<br /><em>made legible.</em></h1><p className="intro">Import a repository and get the map before you make the move. veridexs turns unfamiliar systems into decisions you can act on.</p></section><section className="import-card"><div><p className="card-kicker">START WITH A REPOSITORY</p><h2>Bring a codebase into focus.</h2><p className="muted">Paste a public GitHub URL. We’ll clone a shallow copy and prepare it for intelligence.</p></div><form onSubmit={importRepository}><label htmlFor="repo-url">GitHub repository URL</label><div className="input-row"><input id="repo-url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://github.com/owner/repository" required /><button disabled={submitting}>{submitting ? "Queueing…" : "Import repository"}<span>→</span></button></div>{error && <p className="error">{error}</p>}</form></section><section className="workspace"><div className="section-heading"><div><p className="eyebrow">YOUR WORKSPACE</p><h2>Repositories</h2></div><span className="count">{String(repositories.length).padStart(2, "0")} tracked</span></div>{repositories.length === 0 ? <div className="empty"><span>◎</span><p>No repositories yet.</p><small>Import your first codebase above to begin the architectural read.</small></div> : <div className="repo-grid">{repositories.map((repo) => <article className="repo-card" key={repo.id}><div className="repo-icon">⌁</div><div className="repo-info"><h3>{repo.name}</h3><p>{repo.url.replace("https://github.com/", "")}</p></div><span className={`status ${repo.status}`}>{repo.status}</span><div className="repo-meta"><span>{repo.branch ? `branch / ${repo.branch}` : "preparing branch"}</span><span>{repo.file_count ? `${repo.file_count} files` : "indexing soon"}</span></div></article>)}</div>}</section><footer><span>veridexs / understand deeply</span><span>Phase 01 · Repository intelligence</span></footer></main>;
}
